/* -- Do not recreate as data is loaded here. 
create or replace TABLE SANFORD_EXPORT_ANALYSIS.PUBLIC.EXPORTS_BY_PRODUCT_JUL_23 (
	SPECIES VARCHAR(16777216),
	PRODUCT VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	VOLUME NUMBER(38,0),
	VALUE NUMBER(38,0)
);

create or replace TABLE SANFORD_EXPORT_ANALYSIS.PUBLIC.EXPORTS_BY_PRODUCT_JUL_24 (
	SPECIES VARCHAR(16777216),
	PRODUCT VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	VOLUME NUMBER(38,0),
	VALUE NUMBER(38,0)
);

create or replace TABLE SANFORD_EXPORT_ANALYSIS.PUBLIC.EXPORTS_BY_PRODUCT_JUL_25 (
	SPECIES VARCHAR(16777216),
	PRODUCT VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	VOLUME NUMBER(38,0),
	VALUE NUMBER(38,0)
);
*/

create or replace TABLE SANFORD_EXPORT_ANALYSIS.PUBLIC.EXPORTS_BY_PRODUCT_MERGED (
	SPECIES VARCHAR(16777216),
	PRODUCT VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	VOLUME NUMBER(38,0),
	VALUE NUMBER(38,0),
	REPORTING_YEAR NUMBER(38,0)
);

CREATE OR REPLACE TABLE Dim_Species (
    species_id INT AUTOINCREMENT PRIMARY KEY,
    species_name STRING UNIQUE
);

CREATE OR REPLACE TABLE Dim_Product (
    product_id INT AUTOINCREMENT PRIMARY KEY,
    product_name STRING UNIQUE
);


CREATE OR REPLACE TABLE Dim_Country (
    country_id INT AUTOINCREMENT PRIMARY KEY,
    country_name STRING UNIQUE
);

CREATE OR REPLACE TABLE Dim_Date (
    date_id INT AUTOINCREMENT PRIMARY KEY,
    reporting_year INT UNIQUE
);

CREATE OR REPLACE TABLE Fact_Exports (
    species_id INT,
    product_id INT,
    country_id INT,
    date_id INT,
    volume NUMBER,
    value NUMBER,
    FOREIGN KEY (species_id) REFERENCES Dim_Species(species_id),
    FOREIGN KEY (product_id) REFERENCES Dim_Product(product_id),
    FOREIGN KEY (country_id) REFERENCES Dim_Country(country_id),
    FOREIGN KEY (date_id) REFERENCES Dim_Date(date_id)
);